services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
        - docker-network
    ports:
      - 9000:9000
    develop:
      watch:
        - action: sync
          path: ./
          target: /var/www/html
    depends_on:
      - db
  
  caddy:
    image: caddy:latest
    ports:
      - 81:80
      - 443:443
    volumes:
      - ./:/var/www/html
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - docker-network
    depends_on:
      - app

  db:
    image: mysql:latest
    platform: linux/x86_64
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ea-database
      MYSQL_USER: ea-username
      MYSQL_PASSWORD: ea-password
    networks:
      - docker-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PASSWORD: root
    networks:
      - docker-network

volumes:
  db-data:

networks:
  mysql-phpmyadmin:
  docker-network:
    driver: bridge
